"""updating

Revision ID: 603f491a409e
Revises: 
Create Date: 2018-09-19 16:55:57.947656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603f491a409e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('station_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('forecast_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hourForecast_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'name', name='locations_pkey'),
    sa.UniqueConstraint('name', name='locations_name_key'),
    sa.UniqueConstraint('station_id', name='locations_station_id_key')
    )
    # ### end Alembic commands ###
