"""changed single state column to state_short and state_full

Revision ID: 6464592b54d9
Revises: 603f491a409e
Create Date: 2018-10-02 16:45:49.535952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6464592b54d9'
down_revision = '603f491a409e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state_full', sa.String(length=255), nullable=True),
    sa.Column('station_id', sa.String(length=10), nullable=True),
    sa.Column('forecast_url', sa.String(length=255), nullable=True),
    sa.Column('hourForecast_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('station_id')
    )
    # ### end Alembic commands ###
