"""station_id no longer needs to be unique

Revision ID: 9227624ccded
Revises: 6464592b54d9
Create Date: 2018-10-02 17:06:06.553763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9227624ccded'
down_revision = '6464592b54d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_station_id_key', 'locations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('locations_station_id_key', 'locations', ['station_id'])
    # ### end Alembic commands ###
